data = {
    "hello_list": [
    "hi",
    "hello",
    "hey",
    "greetings",
    "howdy",
    "hiya",
    "what's up",
    "sup",
    "yo",
    "good day",
    "hey there",
],
    "bye_list": [
    "bye",
    "goodbye",
    "see you",
    "later",
    "farewell",
    "take care",
    "see ya",
    "bye-bye",
    "good night",
    "stop",
],
    "open_browser_phrases": [
    "open the browser",
    "launch the browser",
    "open a web browser",
    "start the browser",
    "launch the web browser",
    "open a webpage",
    "open a website",
    "go to a website",
    "navigate to a website",
    "open the internet browser",
    "open a URL",
    "launch a webpage",
    "fire up the browser",
    "access a website",
    "browse to a website",
    "open a new browser window",
    "bring up the browser",
    "pull up the browser",
    "load the browser",
    "open an online page"
],
    "websites" : [
    "google",
    "youtube",
    "facebook",
    "amazon",
    "wikipedia",
    "twitter",
    "instagram",
    "linkedin",
    "netflix",
    "reddit",
    "ebay",
    "pinterest",
    "yahoo",
    "bing",
    "whatsapp",
    "spotify",
    "tiktok",
    "apple",
    "microsoft",
    "cnn"
],
    "play_song_phrases" : [
    "play a song",
    "start the music",
    "play some music",
    "begin the song",
    "play a track",
    "start a tune",
    "put on a song",
    "play a melody",
    "launch the music",
    "turn on the music",
    "play the track",
    "spin a song",
    "queue up a song",
    "stream a song",
    "play that song",
    "kick off the music",
    "put on some tunes",
    "start playing music",
    "play a musical track",
    "play a piece of music"
],

    "math_phrases" : [
    "add",
    "subtract",
    "multiply",
    "divide",
    "calculate",
    "sum",
    "difference",
    "product",
    "quotient",
    "plus",
    "minus",
    "times",
    "divided by",
],

}