data = {
    "hello_list": [
    "hi",
    "hello",
    "hey",
    "greetings",
    "howdy",
    "hiya",
    "what's up",
    "sup",
    "yo",
    "good day",
    "hey there",
],
    "bye_list": [
    "bye",
    "goodbye",
    "see you",
    "later",
    "farewell",
    "take care",
    "see ya",
    "bye-bye",
    "good night",
],
    "open_browser_phrases": [
    "open the browser",
    "launch the browser",
    "open a web browser",
    "start the browser",
    "launch the web browser",
    "open a webpage",
    "open a website",
    "go to a website",
    "navigate to a website",
    "open the internet browser",
    "open a URL",
    "launch a webpage",
    "fire up the browser",
    "access a website",
    "browse to a website",
    "open a new browser window",
    "bring up the browser",
    "pull up the browser",
    "load the browser",
    "open an online page"
],
    "websites" : [
    "google",
    "youtube",
    "facebook",
    "amazon",
    "wikipedia",
    "twitter",
    "instagram",
    "linkedin",
    "netflix",
    "reddit",
    "ebay",
    "pinterest",
    "yahoo",
    "bing",
    "whatsapp",
    "spotify",
    "tiktok",
    "apple",
    "microsoft",
    "cnn"
],

}