import os
import subprocess
import webbrowser

commands_to_open_in_windows = {
    "open File Explorer": lambda: os.system("explorer"),
    "launch Control Panel": lambda: os.system("control"),
    "open Task Manager": lambda: os.system("taskmgr"),
    "start Command Prompt": lambda: os.system("cmd"),
    "launch PowerShell": lambda: os.system("powershell"),
    "open Settings": lambda: os.system("start ms-settings:"),
    "open a folder": lambda path: os.startfile(path),
    "open a specific file": lambda file: os.startfile(file),
    "launch a program": lambda program: subprocess.Popen(program),
    "start Microsoft Edge": lambda: subprocess.Popen("msedge"),
    "open Google Chrome": lambda: subprocess.Popen("chrome"),
    "launch a web browser": lambda url: webbrowser.open(url),
    "open Notepad": lambda: subprocess.Popen("notepad"),
    "launch Calculator": lambda: os.system("calc"),
    "start Microsoft Word": lambda: subprocess.Popen("winword"),
    "open Microsoft Excel": lambda: subprocess.Popen("excel"),
    "launch Microsoft PowerPoint": lambda: subprocess.Popen("powerpnt"),
    "open the Downloads folder": lambda: os.startfile(os.path.expanduser("~/Downloads")),
    "open the Documents folder": lambda: os.startfile(os.path.expanduser("~/Documents")),
    "launch Device Manager": lambda: os.system("devmgmt.msc"),
    "open the Recycle Bin": lambda: os.startfile("shell:RecycleBinFolder"),
    "launch Windows Update": lambda: os.system("start ms-settings:windowsupdate"),
    "open Bluetooth settings": lambda: os.system("start ms-settings:bluetooth"),
    "open Network & Internet settings": lambda: os.system("start ms-settings:network-status"),
    "launch the Snipping Tool": lambda: subprocess.Popen("SnippingTool"),
    "open Paint": lambda: subprocess.Popen("mspaint"),
    "start Windows Media Player": lambda: subprocess.Popen("wmplayer"),
    "open the Volume Mixer": lambda: os.system("sndvol"),
    "open the Windows Store": lambda: subprocess.Popen("ms-windows-store:"),
    "launch the Task Scheduler": lambda: os.system("taskschd.msc"),
    "open Event Viewer": lambda: os.system("eventvwr.msc"),
    "open Disk Management": lambda: os.system("diskmgmt.msc"),
    "launch Remote Desktop Connection": lambda: os.system("mstsc"),
    "open the Run dialog": lambda: os.system("start shell:Appsfolder\\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy!StartMenu"),
    "start Windows Defender": lambda: subprocess.Popen("start windowsdefender:"),
    "open System Information": lambda: os.system("msinfo32"),
    "open Windows Security": lambda: os.system("start windowsdefender:"),
    "open the Start menu": lambda: os.system("start shell:Appsfolder\\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy!StartMenu"),
    "open Windows Explorer": lambda: os.system("explorer"),
}
